project:
  type: website
  output-dir: docs
website:
  title: "Project-Equilibrium"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Minh-AnhHuynh/Project-Equilibrium
      - icon: rss
        href: index.xml
  site-url: https://minh-anhhuynh.github.io/Project-Equilibrium/
  description: "Thinking blog"
format:
  html:
    theme: solar
    css: styles.css

editor: visual

